-- Naming cleanup continuation (see 20260922000007): departments doesn't
-- have config/setting's naming confusion, but user asked for the
-- system_ prefix for consistency with system_access/system_setting —
-- all 3 are System Settings-owned, platform-wide config tables, as
-- opposed to project-owned tables like b_quest_*.
--
-- Unlike setting_project's rename, no function body needs updating
-- here: profiles.department's FK (references public.departments(name)
-- on update cascade, added 20260728000001) and the anon SELECT policy
-- (20260728000005_departments_anon_select.sql) are both schema-level
-- objects tracked by OID, not by name — ALTER TABLE RENAME preserves
-- them automatically. Confirmed via grep: fn_cascade_codename_rename()
-- and no other PL/pgSQL function reference "departments" by literal
-- name (departments doesn't store codenames, so it was never in scope
-- for that trigger anyway).
alter table public.departments rename to system_department;
